Repository VTUL/dlp-access, pull requests merged in 2020-09, with the labels that each got.

#180 Modal accessibility
  package-lock.json
  package.json
  src/css/SearchResult.css
  src/pages/search/SearchFacets.js
Labels: Ready for merge, Ready for review

#181 Refactor image grid to show images for collection and it's children
  amplify/backend/api/collectionarchives/schema.graphql
  amplify/backend/function/collectionTitleEdit/collectionTitleEdit-cloudformation-template.json
  amplify/backend/function/createCollectionHeirarchy/createCollectionHeirarchy-cloudformation-template.json
  amplify/backend/function/createCollectionMap/createCollectionMap-cloudformation-template.json
  amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json
  src/graphql/mutations.js
  src/graphql/queries.js
  src/graphql/schema.json
  src/graphql/subscriptions.js
  src/pages/collections/CollectionItemsLoader.js
Labels: Ready for review, newbackendenv

#185 refactor collection hierarchy sort
  src/pages/collections/SubCollectionsLoader.js
Labels: Ready for review

#186 fix tests
  cypress/integration/search_bar.spec.js
Labels: Ready for review

#182 LIBTD-2321: Create SiteAdmin page to update site configurations with authentication
  package-lock.json
  package.json
  src/App.js
  src/pages/SiteAdmin.js
Labels: Ready for review

#187 Accessibility fixes for WCAG 2.0
  cypress/integration/category_select_checkbox.spec.js
  cypress/integration/multi_select_checkbox_spec.js
  src/components/Collapsible.js
  src/components/Pagination.js
  src/components/Thumbnail.js
  src/css/ListPages.css
  src/css/SearchResult.css
  src/lib/MetadataRenderer.js
  src/pages/collections/CollectionItemsLoader.js
  src/pages/collections/CollectionsListPage.js
  src/pages/collections/CollectionsShowPage.js
  src/pages/search/MasonryView.js
  src/pages/search/SearchFacets.js
  src/pages/search/SearchResults.js
Labels: Ready for review

#189 Refactor functions that iterate through heirarchy to use one query
  src/components/Breadcrumbs.js
  src/lib/fetchTools.js
  src/pages/collections/CollectionsShowPage.js
  src/pages/collections/SubCollectionsLoader.js
Labels: Ready for review

#188 LIBTD-2314: Provide site configuration update function with amplify auth
  src/App.js
  src/components/ContactSection.js
  src/components/Header.js
  src/components/HeaderBreadcrumbs.js
  src/lib/CustomPageRoutes.js
  src/lib/fetchTools.js
  src/pages/AboutPage.js
  src/pages/HomePage.js
  src/pages/PermissionsPage.js
  src/pages/admin/SiteAdmin.js
  src/pages/admin/SiteForm.js
  src/pages/archives/ArchivePage.js
  src/pages/collections/CollectionsListLoader.js
  src/pages/collections/CollectionsShowLoader.js
  src/pages/search/SearchLoader.js
Labels: Ready for review

#190 LIBTD-2304_refactor: Use 'heirarchy_path' attribute to get all the it…
  src/lib/fetchTools.js
  src/pages/admin/SiteForm.js
Labels: Ready for review

#145 Created Related Items section
  cypress/integration/related_items_spec.js
  package-lock.json
  package.json
  src/components/RelatedItems.js
  src/css/RelatedItems.css
  src/pages/archives/ArchivePage.js
Labels: Ready for review
